import React, { useEffect } from 'react';
import { useDispatch } from "react-redux"
import { updateUser } from "../redux/user.slice"
import Head from 'next/head'
import axios from 'axios'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
// import { LandingPageNavbar } from "../components"
const NavBar = dynamic(() => import('../components/shared/LandingPageNavbar'), {
  ssr: false,
})

export default function Home({ status, data }) {
  const dispatch = useDispatch()
  const updatedUserDispatch = () => {
    if (status === 200 && data.is_success) {
      dispatch(updateUser(data.data))
    }
  }
  useEffect(() => {
    updatedUserDispatch()
    // eslint-disable-next-line
  }, [])
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Pakistani Sports</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />
      </div>
    </>
  )
}


export async function getServerSideProps(context) {
  try {
    let token = null;
    if (context.req.cookies && context.req.cookies.token) {
      token = context.req.cookies.token
    }
    if (context.query.token) {
      token = context.query.token
    }
    const response = await axios.get(`${process.env.APP_API_URL}/profile`, {
      headers: {
        'Authorization': token ? token : null
      }
    })
    return {
      props: {
        status: response.status,
        data: response.data
      },
    }
  } catch (error) {
    console.log(error)
    return {
      props: {
        status: 200,
        data: {
          is_success: false,
          message: 'Something went wrong'
        }
      },
    }
  }
}